/*******************************************************************************
 * Copyright (c) 2014 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 *
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 03:18:36 PM GMT 
//


package eu.ddmore.libpharmml.dom.modeldefn;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariabilityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VariabilityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="residualError"/>
 *     &lt;enumeration value="parameterVariability"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VariabilityType")
@XmlEnum
public enum Variability {


	/**
     * 
     *                         Residual error variability.
     *                     
     * @deprecated Since version 0.3. Replaced by RESIDUAL_ERROR.
     */
    @XmlEnumValue("error")
    ERROR("error"),

    /**
     * 
     *                         Model variability.
     *                     
     * @deprecated Since version 0.3. Replaced by PARAMETER_VARIABILITY.
     */
    @XmlEnumValue("model")
    MODEL("model"),
    
    /**
     * 
     *                         Residual error variability.
     *                     
     * 
     */
    @XmlEnumValue("residualError")
    RESIDUAL_ERROR("residualError"),

    /**
     * 
     *                         Parameter variability - random effects.
     *                     
     * 
     */
    @XmlEnumValue("parameterVariability")
    PARAMETER_VARIABILITY("parameterVariability");
    
    private final String value;

    Variability(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Variability fromValue(String v) {
        for (Variability c: Variability.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
