/*******************************************************************************
 * Copyright (c) 2014-2016 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 * 
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 * 
 *  		http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 03:18:36 PM GMT 
//


package eu.ddmore.libpharmml.dom.uncertml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.visitor.Visitor;


/**
 * <p>Java class for ChiSquareDistributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChiSquareDistributionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uncertml.org/3.0}AbstractContinuousUnivariateDistributionType">
 *       &lt;sequence>
 *         &lt;element name="degreesOfFreedom" type="{http://www.uncertml.org/3.0}PositiveNaturalNumberValueType"/>
 *         &lt;element name="truncationLowerInclusiveBoundIG" type="{http://www.uncertml.org/3.0}PositiveRealValueType" minOccurs="0"/>
 *         &lt;element name="truncationUpperInclusiveBoundIG" type="{http://www.uncertml.org/3.0}PositiveRealValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChiSquareDistributionType", propOrder = {
    "degreesOfFreedom",
    "truncationLowerInclusiveBoundIG",
    "truncationUpperInclusiveBoundIG"
})
@XmlSeeAlso({
    ChiSquareDistribution.class
})
public class ChiSquareDistributionType
    extends AbstractContinuousUnivariateDistributionType
{
	
	@XmlTransient
	public static java.lang.String DEFINITION_ELEMENT_URI = "chi-square";

	@Override
	protected java.lang.String getDefinitionElementURI() {
		return DEFINITION_ELEMENT_URI;
	}

    @XmlElement(required = true)
    protected PositiveNaturalNumberValueType degreesOfFreedom;
    protected PositiveRealValueType truncationLowerInclusiveBoundIG;
    protected PositiveRealValueType truncationUpperInclusiveBoundIG;

    /**
     * Gets the value of the degreesOfFreedom property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveNaturalNumberValueType }
     *     
     */
    public PositiveNaturalNumberValueType getDegreesOfFreedom() {
        return degreesOfFreedom;
    }

    /**
     * Sets the value of the degreesOfFreedom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveNaturalNumberValueType }
     *     
     */
    public void setDegreesOfFreedom(PositiveNaturalNumberValueType value) {
        this.degreesOfFreedom = value;
    }

    /**
     * Gets the value of the truncationLowerInclusiveBoundIG property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveRealValueType }
     *     
     */
    public PositiveRealValueType getTruncationLowerInclusiveBoundIG() {
        return truncationLowerInclusiveBoundIG;
    }

    /**
     * Sets the value of the truncationLowerInclusiveBoundIG property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveRealValueType }
     *     
     */
    public void setTruncationLowerInclusiveBoundIG(PositiveRealValueType value) {
        this.truncationLowerInclusiveBoundIG = value;
    }

    /**
     * Gets the value of the truncationUpperInclusiveBoundIG property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveRealValueType }
     *     
     */
    public PositiveRealValueType getTruncationUpperInclusiveBoundIG() {
        return truncationUpperInclusiveBoundIG;
    }

    /**
     * Sets the value of the truncationUpperInclusiveBoundIG property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveRealValueType }
     *     
     */
    public void setTruncationUpperInclusiveBoundIG(PositiveRealValueType value) {
        this.truncationUpperInclusiveBoundIG = value;
    }

	@Override
	public void accept(Visitor visitor) {
		visitor.visit(this);
		
	}

}
