/*******************************************************************************
 * Copyright (c) 2014-2016 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 * 
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 * 
 *  		http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 03:18:36 PM GMT 
//


package eu.ddmore.libpharmml.dom.uncertml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.visitor.Visitor;


/**
 * <p>Java class for MultinomialDistributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultinomialDistributionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uncertml.org/3.0}AbstractDiscreteMultivariateDistributionType">
 *       &lt;sequence>
 *         &lt;element name="numberOfTrials" type="{http://www.uncertml.org/3.0}NaturalNumberValueType"/>
 *         &lt;element name="probabilities" type="{http://www.uncertml.org/3.0}ProbabilityValueType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultinomialDistributionType", propOrder = {
    "numberOfTrials",
    "probabilities"
})
@XmlSeeAlso({
    MultinomialDistribution.class
})
public class MultinomialDistributionType
    extends AbstractDiscreteMultivariateDistributionType
{
	@XmlTransient
	public static java.lang.String DEFINITION_ELEMENT_URI = "multinomial";

	@Override
	protected java.lang.String getDefinitionElementURI() {
		return DEFINITION_ELEMENT_URI;
	}

    @XmlElement(required = true)
    protected NaturalNumberValueType numberOfTrials;
    @XmlElement(required = true)
    protected ProbabilityValueType probabilities;

    /**
     * Gets the value of the numberOfTrials property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalNumberValueType }
     *     
     */
    public NaturalNumberValueType getNumberOfTrials() {
        return numberOfTrials;
    }

    /**
     * Sets the value of the numberOfTrials property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalNumberValueType }
     *     
     */
    public void setNumberOfTrials(NaturalNumberValueType value) {
        this.numberOfTrials = value;
    }

    /**
     * Gets the value of the probabilities property.
     * 
     * @return
     *     possible object is
     *     {@link ProbabilityValueType }
     *     
     */
    public ProbabilityValueType getProbabilities() {
        return probabilities;
    }

    /**
     * Sets the value of the probabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProbabilityValueType }
     *     
     */
    public void setProbabilities(ProbabilityValueType value) {
        this.probabilities = value;
    }

	@Override
	public void accept(Visitor visitor) {
		visitor.visit(this);
		
	}

}
