/*******************************************************************************
 * Copyright (c) 2014-2016 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 * 
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 * 
 *  		http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 03:18:36 PM GMT 
//


package eu.ddmore.libpharmml.dom.commontypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.MasterObjectFactory;
import eu.ddmore.libpharmml.visitor.Visitor;


/**
 * A literal Boolean value for true.
 * 
 * <p>Java class for TrueBooleanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrueBooleanType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}BooleanType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrueBooleanType")
public class TrueBoolean
    extends BooleanValue
{

	@Override
	public String asString() {
		return "true";
	}

	@Override
	public JAXBElement<TrueBoolean> toJAXBElement() {
		return MasterObjectFactory.COMMONTYPES_OF.createTrue(this);
	}

	@Override
	public String valueToString() {
		return "true";
	}

	@Override
	public boolean booleanValue() {
		return true;
	}

	@Override
	public JAXBElement<TrueBoolean> toJAXBElementOfLogicBinOp() {
		return ObjectFactory.getInstance().createTrue(this);
	}

	@Override
	public void accept(Visitor visitor) {
		visitor.visit(this);
	}
	
	public JAXBElement<TrueBoolean> toJAXBElementVectorValue() {
		return ObjectFactory.getInstance().createTrue(this);
	}

}
