/*******************************************************************************
 * Copyright (c) 2014 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 *
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 03:18:36 PM GMT 
//


package eu.ddmore.libpharmml.dom.trialdesign;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;


/**
 * 
 *                 A type that defines the design of the study.   
 *             
 * 
 * <p>Java class for TrialDesignType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrialDesignType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="Structure" type="{http://www.pharmml.org/2013/03/TrialDesign}TrialStructureType" minOccurs="0"/>
 *         &lt;element name="Population" type="{http://www.pharmml.org/2013/03/TrialDesign}PopulationType" minOccurs="0"/>
 *         &lt;element name="IndividualDosing" type="{http://www.pharmml.org/2013/03/TrialDesign}IndividualDosingType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrialDesignType", propOrder = {
    "structure",
    "population",
    "individualDosing"
})
public class TrialDesignType
    extends PharmMLRootType
{

    @XmlElement(name = "Structure")
    protected TrialStructureType structure;
    @XmlElement(name = "Population")
    protected Population population;
    @XmlElement(name = "IndividualDosing")
    protected List<IndividualDosing> individualDosing;

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link TrialStructureType }
     *     
     */
    public TrialStructureType getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrialStructureType }
     *     
     */
    public void setStructure(TrialStructureType value) {
        this.structure = value;
    }

    /**
     * Gets the value of the population property.
     * 
     * @return
     *     possible object is
     *     {@link Population }
     *     
     */
    public Population getPopulation() {
        return population;
    }

    /**
     * Sets the value of the population property.
     * 
     * @param value
     *     allowed object is
     *     {@link Population }
     *     
     */
    public void setPopulation(Population value) {
        this.population = value;
    }

    /**
     * Gets the value of the individualDosing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the individualDosing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndividualDosing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualDosing }
     * 
     * 
     */
    public List<IndividualDosing> getIndividualDosing() {
        if (individualDosing == null) {
            individualDosing = new ArrayList<IndividualDosing>();
        }
        return this.individualDosing;
    }

}
